using System;

public enum PYAudioTags 
{
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_Cancelar,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_Confirmar,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_DesculpeMasEsteNomeJaEstaRegistrado,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_Pular,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_SelecioneSuaTurma,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_TudoTerminado,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_TudoTerminadoAgora,
	Music_ThrowingOffTheBowlines,
	Music_UkuleleWithSleighBells,
	[Obsolete("The audioFile for this tag dont exist!")] SFX_DoubleTouch,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_InvalidNameMsg,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_EscrevaONomeQueDeseja,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_EsteNomeJaEstaRegistrado,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_Registrado,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_ptBR_SelecioneNaListaOu,
	Music_BrightHappyFuture,
	[Obsolete("The audioFile for this tag dont exist!")] B_NaoRegistrado,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Attention,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Continuar,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_DeleteMsg01,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_DeleteMsg02,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_DeleteMsg03,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_DeleteScore,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Easy,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_GameMode,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Hard,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_InvalidNameMsg,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Menu,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_MusicOff,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_MusicOn,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_NarrationOn,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_No,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Normal,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_NovoNome,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Placar,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_PlacarMsg01,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegisteredMsg,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Registrar,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarMsg01,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarMsg02,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarMsg03,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarPop01,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarPop02,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarPop03,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_RegistrarPop04,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Sair,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_SairMsg01,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_SoundOff,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_SoundOn,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_TimeOver,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Voltar,
	[Obsolete("The audioFile for this tag dont exist!")] Voice_Geral_Yes,
	B_05,
	B_AdicionarExercicio,
	B_AguardePreparandoDesenho,
	B_Ajuda,
	B_AtividadeGuardadaSucesso,
	B_AtividadesOpacas,
	B_AtividadesTransparentes,
	B_Attention,
	B_BaldeTinta,
	B_Borracha,
	B_Cancelar,
	B_Carimbo,
	B_CentralDeAtividades,
	B_ComoJogar,
	B_Confirmar,
	B_Continuar,
	B_CopiandoArquivosParaPlaytable,
	B_CriarGrupoAtividades,
	B_DeleteMsg01,
	B_DeleteMsg02,
	B_DeleteMsg03,
	B_DeleteScore,
	B_DesculpeMasEsteNomeJaEstaRegistrado,
	B_DesejaApagar,
	B_DesejaApagarArquivosCopiadosGaleria,
	B_DesejaGuardarEmUmPendrive,
	B_DesejaMesmoExcluirDesenho,
	B_DesejaMesmoGuardar,
	B_DesejaTrocarFolha,
	B_DesenhoApagado,
	B_DesenhoExcluido,
	B_DesenhoGameName,
	B_DesenhoGamePlayPureInHeart,
	B_DesenhoGuardadoSucesso,
	B_DesenhoMenuThrowingOffTheBowlines,
	B_Desfazer,
	B_DrawVoltar,
	B_Easy,
	B_Editar,
	B_Entendi,
	B_ErroOcorreuVerifiquePendrive,
	B_EscolhaImagemColorir,
	B_EscrevaNomeRegistrar,
	B_EscrevaONomeQueDeseja,
	B_EscrevaTituloNomeDesenho,
	B_EsteNomeJaEstaRegistrado,
	B_Exercicios,
	B_Folha,
	B_FormatoDaFolha,
	B_Galeria,
	B_GameMode,
	B_Guardar,
	B_Hard,
	B_InsiraPendrivePlaytable,
	B_InvalidNameMsg,
	B_IssoIraFinalizalo,
	B_Lapis,
	B_Menu,
	B_MusicOff,
	B_MusicOn,
	B_Nao,
	B_NarrationOn,
	B_No,
	B_Normal,
	B_NovoGrupoCriadoSucesso,
	B_NovoNome,
	B_Parabens,
	B_Pendrive,
	B_Pincel,
	B_PinturaGameName,
	B_PinturaGamePlayFingerPaint,
	B_PinturaMenuUkuleleWithSleighBells,
	B_Placar,
	B_PlacarMsg01,
	B_ProcurandoArquivosPendrive,
	B_Pular,
	B_Registrado,
	B_Registrar,
	B_RegistrarMsg02,
	B_RegistrarPop01,
	B_RegistrarPop02,
	B_RegistrarPop03,
	B_Regua,
	B_Sair,
	B_SairMsg01,
	B_SalvarAtividadesPendrive,
	B_SelecioneNaListaOu,
	B_SelecioneSuaTurma,
	B_SFX_Apagar,
	B_SFX_Bucket,
	B_SFX_Click,
	B_SFX_DeleteAll,
	B_SFX_Desfazer,
	B_SFX_Eraser,
	B_SFX_Exit,
	B_SFX_GuardadoErrado,
	B_SFX_GuardadoSucesso,
	B_SFX_MainMenuSair,
	B_SFX_Pencil,
	B_SFX_SaveError,
	B_SFX_SaveSucess,
	B_Sim,
	B_SoundOff,
	B_SoundOn,
	B_Terminei,
	B_Textura,
	B_TimeOver,
	B_TodosArquivosCopiadosSucesso,
	B_TransferirExercicio,
	B_TudoTerminado,
	B_TudoTerminadoAgora,
	B_Voltar,
	B_Yes,
	None,
	B_Informações,
	B_JogadorNãoRegistrado,
}